src: "C:/Users/User/OneDrive/Desktop/UROPS/tests/test" #C:/Users/User/OneDrive/Desktop/UROPS/hellingertest /home/stumerv/test
distmeasure: "Tamura" # ["Leven", "Raw", "JC", "K2P", "Tamura", "Phylo"]
MDS: "noMDS" # ["MDS", "noMDS"]
clustering: "Agglomerative" #["OPTICS", "Kmeans", "Agglomerative"]
numclusters: 4
